module.exports = {
  DEV: {
    AccountSid: 'ACXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX',
    ApiKey: 'SKXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX',
    ApiSecret: 'XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX',
    WorkspaceSid: 'WSXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX',
    ChatServiceSid: 'ISXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX',
  },
  STG: {
    AccountSid: 'ACXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX',
    ApiKey: 'SKXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX',
    ApiSecret: 'XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX',
    WorkspaceSid: 'WSXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX',
    ChatServiceSid: 'ISXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX',
  }
}